-- ============================================================================
-- MIGRATION 001: Initial Schema - Bot ISP de Ventas
-- ============================================================================
-- Descripción: Schema completo para gestionar clientes, planes, ventas y 
--              activaciones en diferentes campamentos/zonas
-- Seguridad: Usa RLS (Row Level Security) en Supabase
-- ============================================================================

-- 1. TABLA DE CONFIGURACIÓN GLOBAL
CREATE TABLE IF NOT EXISTS configuracion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  valor TEXT NOT NULL,
  descripcion TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. TABLA DE PLANES (Planes disponibles)
CREATE TABLE IF NOT EXISTS planes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,           -- "Plan Basic", "Plan Pro", etc
  descripcion TEXT,
  velocidad_mbps INT,                    -- Velocidad en Mbps
  tarifa_diaria NUMERIC NOT NULL DEFAULT 1.00, -- S/1.00 por día
  estado TEXT DEFAULT 'activo',          -- 'activo', 'inactivo'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. TABLA DE CAMPAMENTOS/ZONAS
CREATE TABLE IF NOT EXISTS campamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,           -- "Campamento Cocha", "Zona Norte", etc
  descripcion TEXT,
  router_ip TEXT NOT NULL,               -- IP del MikroTik para esta zona
  router_puerto INT DEFAULT 8799,
  ubicacion TEXT,                        -- Ubicación geográfica
  estado TEXT DEFAULT 'activo',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. TABLA DE CLIENTES
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  whatsapp_id TEXT NOT NULL UNIQUE,      -- +51999888777
  nombre TEXT,
  contacto TEXT,                         -- Nombre contacto
  saldo NUMERIC DEFAULT 0,               -- Saldo a favor
  estado TEXT DEFAULT 'activo',          -- 'activo', 'inactivo', 'bloqueado'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 4. TABLA DE VENTAS (Historial de compras)
CREATE TABLE IF NOT EXISTS ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  whatsapp_id TEXT NOT NULL,
  plan_id BIGINT,
  campamento_id BIGINT,
  
  -- Información de la solicitud
  dias_solicitados INT NOT NULL DEFAULT 1,  -- Cuántos días pidió el cliente (1, 5, 7, 30, etc)
  tarifa_diaria NUMERIC NOT NULL DEFAULT 1.00, -- S/1.00 por día
  monto NUMERIC GENERATED ALWAYS AS (dias_solicitados * tarifa_diaria) STORED, -- Cálculo automático
  
  estado TEXT DEFAULT 'pendiente',       -- 'pendiente', 'aprobado', 'rechazado'
  foto_comprobante TEXT,                 -- URL de la foto del pago
  metodo_pago TEXT,                      -- 'yape', 'plin', 'transferencia', etc
  
  -- Información de la activación
  fecha_inicio_activacion TIMESTAMP WITH TIME ZONE,  -- Cuándo se activa
  fecha_fin_activacion TIMESTAMP WITH TIME ZONE,     -- Cuándo vence
  usuario_hotspot TEXT,                  -- Usuario creado en MikroTik
  activo BOOLEAN DEFAULT FALSE,           -- Si está actualmente activo
  
  -- Campos adicionales para ChatGPT + MikroTik dinámico
  usuario_mikrotik TEXT,                 -- Usuario guardado desde ChatGPT
  plan_solicitado TEXT,                  -- Plan solicitado desde ChatGPT
  
  -- Auditoría
  aprobado_por TEXT,                     -- Usuario admin que aprobó
  fecha_aprobacion TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 5. TABLA DE PRUEBAS (1 día gratis antes de pagar)
CREATE TABLE IF NOT EXISTS pruebas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  whatsapp_id TEXT NOT NULL REFERENCES clientes(whatsapp_id) ON DELETE CASCADE,
  campamento_id BIGINT NOT NULL REFERENCES campamentos(id),
  
  usuario_hotspot TEXT NOT NULL UNIQUE, -- Usuario temporal en MikroTik
  contrasena TEXT NOT NULL,
  
  fecha_inicio TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  fecha_fin TIMESTAMP WITH TIME ZONE,    -- 1 día después de inicio
  activa BOOLEAN DEFAULT TRUE,
  convertida_a_venta BOOLEAN DEFAULT FALSE, -- Se convirtió en venta pagada
  venta_id BIGINT REFERENCES ventas(id), -- Link a la venta si se convirtió
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 6. TABLA DE ACTIVACIONES (Historial de activaciones)
CREATE TABLE IF NOT EXISTS activaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id BIGINT NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
  
  usuario_hotspot TEXT NOT NULL,
  estado TEXT DEFAULT 'activa',          -- 'activa', 'expirada', 'cancelada'
  
  fecha_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
  fecha_fin TIMESTAMP WITH TIME ZONE NOT NULL,
  fecha_expiracion_real TIMESTAMP WITH TIME ZONE, -- Cuándo se desactivó realmente
  
  motivo_cancelacion TEXT,               -- Razón si fue cancelada
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 7. TABLA DE TRANSACCIONES (Movimientos de dinero)
CREATE TABLE IF NOT EXISTS transacciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  whatsapp_id TEXT NOT NULL REFERENCES clientes(whatsapp_id) ON DELETE CASCADE,
  venta_id BIGINT REFERENCES ventas(id),
  
  tipo TEXT NOT NULL,                    -- 'pago', 'reembolso', 'ajuste', 'abono'
  monto NUMERIC NOT NULL,
  descripcion TEXT,
  
  comprobante_url TEXT,                  -- Para pagos
  aprobado_por TEXT,                     -- Admin que aprobó
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- ============================================================================
-- ÍNDICES para mejor rendimiento
-- ============================================================================

CREATE INDEX idx_ventas_whatsapp ON ventas(whatsapp_id);
CREATE INDEX idx_ventas_estado ON ventas(estado);
CREATE INDEX idx_ventas_plan ON ventas(plan_id);
CREATE INDEX idx_ventas_campamento ON ventas(campamento_id);
CREATE INDEX idx_pruebas_whatsapp ON pruebas(whatsapp_id);
CREATE INDEX idx_pruebas_activa ON pruebas(activa);
CREATE INDEX idx_activaciones_estado ON activaciones(estado);
CREATE INDEX idx_activaciones_venta ON activaciones(venta_id);
CREATE INDEX idx_transacciones_whatsapp ON transacciones(whatsapp_id);
CREATE INDEX idx_transacciones_tipo ON transacciones(tipo);

-- ============================================================================
-- TRIGGER: Actualizar updated_at automáticamente
-- ============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc', NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql
SET search_path = pg_catalog, public;

CREATE TRIGGER trigger_update_clientes BEFORE UPDATE ON clientes
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_update_planes BEFORE UPDATE ON planes
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_update_campamentos BEFORE UPDATE ON campamentos
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_update_ventas BEFORE UPDATE ON ventas
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_update_pruebas BEFORE UPDATE ON pruebas
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_update_activaciones BEFORE UPDATE ON activaciones
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- RLS (Row Level Security) - Enable on all tables
-- ============================================================================

ALTER TABLE configuracion ENABLE ROW LEVEL SECURITY;
ALTER TABLE planes ENABLE ROW LEVEL SECURITY;
ALTER TABLE campamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE pruebas ENABLE ROW LEVEL SECURITY;
ALTER TABLE activaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE transacciones ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- DATA INICIAL: Configuración, Planes y Campamentos
-- ============================================================================

-- Configuración global
INSERT INTO configuracion (nombre, valor, descripcion) VALUES
('tarifa_diaria_soles', '1.00', 'Tarifa diaria en soles (S/1.00 por día)'),
('moneda', 'PEN', 'Moneda: Peruvian Sol'),
('empresa_nombre', 'Bot ISP', 'Nombre de la empresa')
ON CONFLICT (nombre) DO NOTHING;

-- Planes por defecto (ahora sin duracion_dias, usa tarifa diaria)
INSERT INTO planes (nombre, descripcion, velocidad_mbps, tarifa_diaria) VALUES
('Plan Básico', 'Acceso básico a internet (S/1.00 por día)', 5, 1.00),
('Plan Pro', 'Plan intermedio con mejor velocidad (S/1.00 por día)', 10, 1.00),
('Plan Premium', 'Velocidad máxima (S/1.00 por día)', 25, 1.00)
ON CONFLICT (nombre) DO NOTHING;

-- Campamentos/Zonas (al menos uno por defecto)
INSERT INTO campamentos (nombre, descripcion, router_ip, ubicacion) VALUES
('Principal', 'Zona principal de operaciones', '192.168.1.1', 'Principal')
ON CONFLICT (nombre) DO NOTHING;

-- ============================================================================
-- COMENTARIOS DE DOCUMENTACIÓN
-- ============================================================================

COMMENT ON TABLE configuracion IS 'Configuración global del sistema (tarifa diaria, moneda, etc)';
COMMENT ON TABLE clientes IS 'Registro de clientes que contratan servicios';
COMMENT ON TABLE planes IS 'Planes disponibles con tarifa diaria (S/1.00 por día)';
COMMENT ON TABLE campamentos IS 'Ubicaciones/zonas donde se ofrecen servicios';
COMMENT ON TABLE ventas IS 'Histórico de compras y pagos realizados';
COMMENT ON TABLE pruebas IS 'Períodos de prueba gratis (1 día)';
COMMENT ON TABLE activaciones IS 'Historial detallado de activaciones';
COMMENT ON TABLE transacciones IS 'Movimientos de dinero y reembolsos';

COMMENT ON COLUMN ventas.dias_solicitados IS 'Cuántos días pidió el cliente (1, 5, 7, 30, etc)';
COMMENT ON COLUMN ventas.monto IS 'Calculado automáticamente: dias_solicitados * tarifa_diaria';
COMMENT ON COLUMN ventas.activo IS 'TRUE = actualmente activo, FALSE = vencido o cancelado';
COMMENT ON COLUMN ventas.estado IS 'pendiente = esperando pago, aprobado = pagado, rechazado = pago rechazado';
COMMENT ON COLUMN pruebas.convertida_a_venta IS 'TRUE si el cliente pasó la prueba y pagó';
COMMENT ON COLUMN planes.tarifa_diaria IS 'Tarifa diaria en soles (S/1.00 recomendado)';
